echo "---build start---"

node {
    stage('Clone') {
        echo '>>> Git repository Clone'
        git branch: 'feature/jenkins', credentialsId: '6b0913f3-9133-41d9-bbf1-1c0baaafb86b' , url: 'git@github.com:Oh-JunYoung/CowAPI.git'
    }

    stage('Move to Path') {
        echo '>>> Move to Deploy Path'
        sh './jenkins/MovePath.sh'
    }

    stage('Pull') {
        echo '>>> Git repository Clone'
        sh './jenkins/GitPull.sh'
    }

    stage('Build') {
        echo '>>> Gradle project Build'
        sh './jenkins/Build.sh'
    }

    stage('Test') {
        echo '>>> Gradle project Test'
        sh './jenkins/Test.sh'
    }

    stage('Kill') {
        echo '>>> Gradle project Deploy'
        sh './jenkins/KillProcess.sh'
    }

    stage('Deploy') {
        echo '>>> Gradle project Deploy'
        sh './jenkins/Deploy.sh'
    }
}